### ISSUE TITLE
'wc_env_manager container build' is failing

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/wc_env_manager#11] opened 2018-10-20 12:33 UTC
'wc_env_manager container build' has stopped working on my Mac. I don't know why, as I don't believe that I've changed any of the code it uses. 

This is a critical problem because I'm relying on docker containers for my wc_sim development. I will try reinstalling wc_utils and wc_env_manager now.

Here's a trace:

    Script started on Sat Oct 20 08:19:40 2018
    bash-3.2$ wc_env_manager container build
    Traceback (most recent call last):
      File "/anaconda3/bin/wc_env_manager", line 11, in <module>
        sys.exit(main())
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 230, in main
        app.run()
      File "/anaconda3/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
        return_val = self.controller._dispatch()
      File "/anaconda3/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 806, in _dispatch
        return func()
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 140, in build
        mgr = wc_env_manager.core.WcEnvManager({'verbose': VERBOSE})
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/core.py", line 81, in __init__
        'wc_env_manager': config or {}})['wc_env_manager']
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/config/core.py", line 39, in get_config
        return wc_utils.config.ConfigManager(paths).get_config(extra=extra, context=context)
      File "/anaconda3/lib/python3.6/site-packages/wc_utils/config/core.py", line 127, in get_config
        raise ExtraValuesError(config)
      File "/anaconda3/lib/python3.6/site-packages/wc_utils/config/core.py", line 284, in __init__
        the_section = config[section]
      File "/anaconda3/lib/python3.6/site-packages/configobj.py", line 554, in __getitem__
        val = dict.__getitem__(self, key)
    KeyError: 'container'
    bash-3.2$ wc_env_manager -h
    usage: wc_env_manager [-h] [-d] [-q] [-v]
                          {container,image,base-image,build,pull,push,remove} ...

    Whole-cell modeling environment manager

    optional arguments:
      -h, --help            show this help message and exit
      -d, --debug           full application debug mode
      -q, --quiet           suppress all console output
      -v, --version         show program's version number and exit

    sub-commands:
      {container,image,base-image,build,pull,push,remove}
        container           container controller
        image               image controller
        base-image          base-image controller
        build               Build base image, image, and container
        pull                Pull base image and image
        push                Push base image and image
        remove              Remove base image, image, and containers
    bash-3.2$ wc_env_manager container
    usage: wc_env_manager container [-h] {build,remove} ...

    Build and remove containers of `wc_env`

    optional arguments:
      -h, --help      show this help message and exit

    sub-commands:
      {build,remove}
        build         Build container
        remove        Remove container
    bash-3.2$ pip show wc_utils
    Name: wc-utils
    Version: 0.0.1a5
    Summary: Utilities for whole-cell modeling
    Home-page: https://github.com/KarrLab/wc_utils
    Author: Karr Lab
    Author-email: karr@mssm.edu
    License: MIT
    Location: /anaconda3/lib/python3.6/site-packages
    Requires: mendeleev, requests, log, diskcache, enum34, six, numpy, qualname, gitpython, setuptools, pyexcel, attrdict, pyexcel-io, openpyxl, pint, pyyaml, configobj, abduct
    Required-by: wc-env-manager
    bash-3.2$ pip show wc_env_manager
    Name: wc-env-manager
    Version: 0.0.1
    Summary: Tools for managing computing environments for whole-cell modeling
    Home-page: https://github.com/KarrLab/wc_env_manager
    Author: Karr Lab
    Author-email: karr@mssm.edu
    License: MIT
    Location: /Users/arthur_at_sinai/.local/lib/python3.6/site-packages
    Requires: pkg-utils, gitpython, cement, configobj, wc-utils, python-dateutil, requirements-parser, docker, pyyaml, jinja2
    Required-by: 
    bash-3.2$ pip show cement
    Name: cement
    Version: 3.0.0
    Summary: CLI Framework for Python
    Home-page: http://builtoncement.org
    Author: Data Folk Labs, LLC
    Author-email: derks@datafolklabs.com
    License: BSD
    Location: /anaconda3/lib/python3.6/site-packages
    Requires: 
    Required-by: wc-env-manager
    bash-3.2$ wc_env_manager container remove
    Traceback (most recent call last):
      File "/anaconda3/bin/wc_env_manager", line 11, in <module>
        sys.exit(main())
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 230, in main
        app.run()
      File "/anaconda3/lib/python3.6/site-packages/cement/core/foundation.py", line 916, in run
        return_val = self.controller._dispatch()
      File "/anaconda3/lib/python3.6/site-packages/cement/ext/ext_argparse.py", line 806, in _dispatch
        return func()
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/__main__.py", line 147, in remove
        mgr = wc_env_manager.core.WcEnvManager({'verbose': VERBOSE})
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/core.py", line 81, in __init__
        'wc_env_manager': config or {}})['wc_env_manager']
      File "/Users/arthur_at_sinai/.local/lib/python3.6/site-packages/wc_env_manager/config/core.py", line 39, in get_config
        return wc_utils.config.ConfigManager(paths).get_config(extra=extra, context=context)
      File "/anaconda3/lib/python3.6/site-packages/wc_utils/config/core.py", line 127, in get_config
        raise ExtraValuesError(config)
      File "/anaconda3/lib/python3.6/site-packages/wc_utils/config/core.py", line 284, in __init__
        the_section = config[section]
      File "/anaconda3/lib/python3.6/site-packages/configobj.py", line 554, in __getitem__
        val = dict.__getitem__(self, key)
    KeyError: 'container'

**Comment by artgoldberg** [comment] 2018-10-20 13:13
Hi Jonathan

I found a work-around with `docker restart` and I'm now using a previously built container (trace below), so this is no longer critical.

However, despite reinstalling wc_utils and wc_env_manager, I was unable to get `wc_env_manager container build` to work. I'll revisit this when I return from my campaign vacation after ICSB.

    [Users/arthur_at_sinai]$ docker container ls -a
    CONTAINER ID        IMAGE                   COMMAND                 CREATED             STATUS                      PORTS                    NAMES
    4a41c15fc181        karrlab/wc_env          "bash"                  6 days ago          Exited (255) 12 hours ago   0.0.0.0:8888->8888/tcp   jupyter_container
    5951d45802a4        karrlab/wc_env          "bash"                  6 days ago          Created                                              adoring_mendeleev
    7f8417aa7944        bmse-hw4-docker         "/bin/sh -c \"bash\""   12 days ago         Exited (0) 12 days ago                               angry_jang
    592c91a1ef7e        df8334e26442            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 12 days ago                               gifted_fermi
    e5916d7f077a        df8334e26442            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               amazing_chandrasekhar
    11b7abeff9d4        36a7ce7b6075            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               thirsty_hypatia
    98e1622d3470        36a7ce7b6075            "bash"                  13 days ago         Exited (0) 13 days ago                               relaxed_mestorf
    6a83b8a98b95        36a7ce7b6075            "bash"                  13 days ago         Exited (0) 13 days ago                               loving_meninsky
    a19bd8708db5        36a7ce7b6075            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               distracted_shockley
    f1db8eb254dd        fe9e3067be8a            "bash"                  13 days ago         Exited (0) 13 days ago                               nervous_euclid
    bb007bf5c386        hello-world             "/hello"                13 days ago         Exited (0) 13 days ago                               practical_carson
    966df6e6cb58        karrlab/wc_env:latest   "bash"                  2 weeks ago         Exited (255) 12 hours ago                            wc_env-2018-10-02-09-48-28
    [Users/arthur_at_sinai]$ docker restart wc_env-2018-10-02-09-48-28
    wc_env-2018-10-02-09-48-28
    [Users/arthur_at_sinai]$ docker container ls -a
    CONTAINER ID        IMAGE                   COMMAND                 CREATED             STATUS                      PORTS                    NAMES
    4a41c15fc181        karrlab/wc_env          "bash"                  6 days ago          Exited (255) 12 hours ago   0.0.0.0:8888->8888/tcp   jupyter_container
    5951d45802a4        karrlab/wc_env          "bash"                  6 days ago          Created                                              adoring_mendeleev
    7f8417aa7944        bmse-hw4-docker         "/bin/sh -c \"bash\""   12 days ago         Exited (0) 12 days ago                               angry_jang
    592c91a1ef7e        df8334e26442            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 12 days ago                               gifted_fermi
    e5916d7f077a        df8334e26442            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               amazing_chandrasekhar
    11b7abeff9d4        36a7ce7b6075            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               thirsty_hypatia
    98e1622d3470        36a7ce7b6075            "bash"                  13 days ago         Exited (0) 13 days ago                               relaxed_mestorf
    6a83b8a98b95        36a7ce7b6075            "bash"                  13 days ago         Exited (0) 13 days ago                               loving_meninsky
    a19bd8708db5        36a7ce7b6075            "/bin/sh -c \"bash\""   13 days ago         Exited (0) 13 days ago                               distracted_shockley
    f1db8eb254dd        fe9e3067be8a            "bash"                  13 days ago         Exited (0) 13 days ago                               nervous_euclid
    bb007bf5c386        hello-world             "/hello"                13 days ago         Exited (0) 13 days ago                               practical_carson
    966df6e6cb58        karrlab/wc_env:latest   "bash"                  2 weeks ago         Up 15 seconds                                        wc_env-2018-10-02-09-48-28
    [Users/arthur_at_sinai]$ docker exec --interactive --tty wc_env-2018-10-02-09-48-28 bash
    root@966df6e6cb58:/# cd /root/host/Documents/wc_dev_repos/wc_env_manager/

**Comment by jonrkarr** [comment] 2018-10-22 17:50
I suspect the problem is a mal-formed configuration file. This is
surprising because I've only changed the schema a little. See my example
below. Do you have the same indentation for the triple quotes? Also the
nested subsections have to come after the nested attributes (this comes
from a limitation with configobj).

wc_env_manager.cfg

> [wc_env_manager]
>     [[container]]
>         python_packages = '''
>         -e /root/host/Documents/datanator
>         -e /root/host/Documents/wc_utils
>         -e /root/host/Documents/wc_kb
>         -e /root/host/Documents/wc_lang
>         -e /root/host/Documents/wc_model_gen
>         '''
>         [[[paths_to_mount]]]
>             [[[[${HOME}/Documents]]]]
>                 bind = /root/host/Documents
>                 mode = rw


Some other thoughts:

   - You seem to be using an older revision of wc_env_manager. *Please pull
   the latest version of wc_env_manager.*
   - It seems that your configuration file is clashing with the schema for
   the configuration file. Please follow the configuration file example below.
   - I realize the config error isn't information. I'll try to work on that.
   - I can't tell if you have the latest version of wc_utils, but I doubt
   this is the problem.
   - The version of cement looks fine.

Jonathan

**Comment by jonrkarr** [comment] 2018-10-22 19:13
This is a problem with error reporting in wc_utils. This is now fixed. To make debugging config files easier, wc_utils will also now report the sources of the configuration values.

**Closed by jonrkarr** 2018-10-22 19:13 UTC
Labels: bug
